### ISSUE TITLE
关于事件问题

### ISSUE THREAD

**Issue by liangtongzhuo** [bobiscool/wxDraw#1]
非常感谢作者开源这个框架。
我有一个问题，Canvas 上的事件你是怎么处理了？  是把绘制出来的图形的宽高记录下来，自己判断的吧？那就有另外一个问题，假如我往 Canvas 上绘制图片，我怎么确定我点击到的是在图片上。  图片是不规则带，一部分是带透明的。

**Comment by bobiscool** [comment]
浏览器上Canvas 带Api   isPointInPath可以做这个检测,但是在小程序里面没有这个，不是记录宽高「不是所有都有宽高 比如曲线 多边形 不规则图形 」而是记录所有点位，自己用数学方法来计算是否在里面
