### ISSUE TITLE
渐变不支持线条么？

### ISSUE THREAD

**Issue by xcchcaptain** [bobiscool/wxDraw#10]
比如我想画一条渐变色的弧
`let epointYes=new Shape('circle',{x:60,y:250,r:35,strokeStyle:"#d9f912",lineWidth:5,sA:0,eA:Math.PI*2*(that.data.reportData.totalScore/100),lineCap:"round",needGra:'line',gra:[[0,"#d9f912"],[0.2,'#bbf524'],[0.4,'#93ef42'],[0.6,"#7aeb51"],[1,'#4ae474']]},'stroke',false);`
不启作用，是否有办法支持？

**Comment by bobiscool** [comment]
不支持哈 不好意思
