### ISSUE TITLE
文档没写清楚

### ISSUE THREAD

**Issue by oliver34** [bobiscool/wxDraw#11]
Shape 支持哪些形状，不同形状都有哪些参数，参数是什么意思都没有写清楚

**Comment by bobiscool** [comment]
你确定 你访问了 这个 ？？
http://project.ueflat.xyz/

**Comment by bobiscool** [comment]
http://project.ueflat.xyz/#/api/Shapes

**Comment by sichenguo** [comment]
文档站点挂了 老哥
