### ISSUE TITLE
这是一个 canvas2wxcanvas 的封装吗？

### ISSUE THREAD

**Issue by NoraGithub** [bobiscool/wxDraw#14]
您好，请问 小程序canvas api 和 canvas 原生api 有多大差异呢？这是一个对小程序canvas的封装吗？是不是使用了可以对其他canvas库进行使用吖？如果不是的话，做这种转换的可能性和难度从您专业的角度来看请问有多大呢？（有一些业务需求）

**Comment by bobiscool** [comment]
wxDraw 不是 一个playfill 库，也就是说不是 canvas2wxcanvas的封装，wxDraw 是对wxCanvas 底层的 api 进行了封装，使它具有事件，交互，动画以及创建复杂图形的能力。

wxCanvas api 与标准 Api 差异在于不完整，特别是有几个极为重要的 api，wxCanvas 上没有或者是不完全。
举例:

- isPointInpath 这是通过调用底层语言 检测像素点是否在路径里面的
- drawImage(image,sX,sY,sW,sH,dX,dY,dW,dH)  「绘制图像，在 wxCanvas 里面 直接被阉割成只接受 前面五个参数」

这两个地方，让 wxCanvas 没法支持
- 超精确的点击检测，比如 我的 线条点击 事件，「我所有的点击事件都是使用数学算法来解决的」
- Sprites 动画 「这也没法做小游戏了」

这些 api 只能官方原生支持，所谓的转化，几乎没法进行，抛开能不能实现不说，即使实现了，性能上极其差。
