### ISSUE TITLE
旋转动画方向

### ISSUE THREAD

**Issue by Neras** [bobiscool/wxDraw#15]
请问动画方向，就旋转来说，只有逆时针方向吗

**Comment by bobiscool** [comment]
由于 我的图形绘制方法与角度 关系紧密 为了不造成混乱，所以没有引入逆时针动画，但是你完全可以把要正的角度 改成负的角度，这样也可以代替逆时针动画

**Comment by Neras** [comment]
好的，谢谢。主要是某些奇葩的业务需求。我多尝试一下。
