### ISSUE TITLE
图集功能有在roadmap里面吗？

### ISSUE THREAD

**Issue by Bluebang** [bobiscool/wxDraw#16]
准备什么时候支持图集呢？我看小程序里面的drawImage里面是有9个参数的，可以支持显示部分图片区域，可以用图集功能。

**Comment by bobiscool** [comment]
支持 ？？？
<img width="709" alt="drawimage_ _" src="https://user-images.githubusercontent.com/9073321/34368825-03ed7fc8-eaf2-11e7-8dcd-66fbf2cfd16d.png">

**Comment by bobiscool** [comment]
为啥 我看到文档 就五个参数

**Comment by Bluebang** [comment]
![qq 20171227103958](https://user-images.githubusercontent.com/22443960/34368917-ca5870fa-eaf2-11e7-9e60-5dd91a19d922.png)


虽然接口没写出来，但是底层是能用的。如果以前不能用，估计是悄悄更新了

**Comment by bobiscool** [comment]
这。。。我当时页试了下 没有 ，谢谢提醒👍，那我得好好花一段时间添加一个新的对象了
