### ISSUE TITLE
嗨，如何更改Shape里面的图片引用？

### ISSUE THREAD

**Issue by Bluebang** [bobiscool/wxDraw#17]
在精灵图功能出来之前，还是想要一个帧动画的效果。我想就用单图实现。创建好的Shape如何修改图片的引用呢？

**Comment by bobiscool** [comment]
因为刚开始没有考虑精灵图 所以 src 也就没有设置 可以更改的 不好意思 后期加上

**Comment by Bluebang** [comment]
加油。
