### ISSUE TITLE
shape resize  support?

### ISSUE THREAD

**Issue by notedit** [bobiscool/wxDraw#18]
can we do shape resize now?

**Comment by bobiscool** [comment]
你的意思是 放大 缩小吧， 目前我的图形旋转平移都是  向量点外加矩阵计算 的，如果要添加放大 需要重新加一套算法，所以这一版本还没有，会在后期添加。

**Comment by notedit** [comment]
是的.

我们在用https://github.com/kangax/fabric.js  搭建了一个多人共享白板,  
接下来计划做小程序的版本.

几个我们会需要的feature,

1, shape to  json   json to json    
2, 手势操作,shape放大缩小 以及整体canvas的放大缩小

fabric 是一个功能非常强大的canvas库,  不知道wxDraw未来的开发方向是怎样的

**Comment by bobiscool** [comment]
wxDraw 现在是我一个人维护 可能暂时没法做到那么强大😂 ，不过你实在要在微信小程序上使用强大的 canvas 库，最近出了一个小游戏  是属于微信小程序下面的一个子集，他里面的 canvas与原生的 canvas 差别不大，fabric 可能改一改就可以用了。「这是腾讯负责小程序还有小游戏技术架构的人跟我说的」

**Comment by notedit** [comment]
有看小游戏的canvas,  已经是功能完备的canvas api了,  不知道什么时候对小程序开放. 这个你有内部消息么

**Comment by bobiscool** [comment]
这应该是运营的事 他们也不知道
