### ISSUE TITLE
老哥，animate start之后能不能在start一次

### ISSUE THREAD

**Issue by microcisco** [bobiscool/wxDraw#20]
老哥，animate start之后能不能在start一次类似这样
    img.animate({x: '+=100'}, { duration: 1000 })
      // .animate({ w: 100 }, { duration: 1000 })
    .start()

      setTimeout(function () {
        console.log(123);

        // img.updateOption({ x: 200})
        // img.stop();

          img.animate({x: '-=100'}, { duration: 1000 })
          // .animate({ w: 100 }, { duration: 1000 })
              .start()

      }, 2000);

**Comment by bobiscool** [comment]
你只需要在 start 里面传你需要动画的次数就行了 
start(2)就行

**Comment by microcisco** [comment]
嗯，这样确实可以。但我想的是我点击一下方块就左移10px这样，所以不可能吧animate一次性写完再start

**Comment by bobiscool** [comment]
那就 onclick 里面回调 里面就可以执行动画 这样每次点击就会自定执行一次动画呀
或者 onclick 里面 执行 setOption就行啊

**Comment by bobiscool** [comment]
说错了 事件绑定不是 onclick
例子

http://project.ueflat.xyz/#/api/Event

**Comment by microcisco** [comment]
老哥，我刚刚发现一个神奇的现象：
这么写img会右移动200px
    img.animate({x: '+=100'}, { duration: 1000, onEnd: ()=>{
          img.animate({x: '-=100'},{duration: 1000}).start()
      }}).start();

但是这么写就只会移动100px
      img.animate({x: '+=100'}, { duration: 1000, onEnd: ()=>{
          // img.animate({x: '-=100'},{duration: 1000}).start()
      }}).start();
      setTimeout(()=>{
          img.animate({x: '-=100'},{duration: 1000}).start()
      }, 2000)

这是为什么呀

**Comment by bobiscool** [comment]
我待会儿 看看

**Comment by microcisco** [comment]
嗯嗯，辛苦了哈

**Comment by bobiscool** [comment]
修复了 第一个问题 你试试 
  
第二个 我再看看

**Comment by microcisco** [comment]
谢谢啦，不过由于赶时间我自己撸了一套动画库，我整理下也发上去，我是借鉴的cocos的实现。
