### ISSUE TITLE
安卓微信多个动画同时播放会卡死

### ISSUE THREAD

**Issue by cangege** [bobiscool/wxDraw#25]
安卓微信多个动画同时播放会卡死，ios只能播放第一次

**Comment by arminWork** [comment]
android和ios下都没有响应tap事件，ios下touchstart和touchend事件点很多次偶尔会有一次响应

**Comment by bobiscool** [comment]
实在不好意思 手上没有 iPhone 所以 iphone 调试还有点跟不上  安卓正在解决性能的问题
