### ISSUE TITLE
tap事件没响应

### ISSUE THREAD

**Issue by arminWork** [bobiscool/wxDraw#29]
android和ios下都没有响应tap事件，ios下touchstart和touchend事件点很多次偶尔会有一次响应

**Comment by bobiscool** [comment]
能 帖点代码吗？

**Comment by arminWork** [comment]
我就是用的示例，android和ios都试了，微信版本6.6.1，不知道跟微信的版本有关系没

**Comment by bobiscool** [comment]
有 啥报错吗？

**Comment by arminWork** [comment]
没有报错，canvas的tap不响应

**Comment by imtiantian** [comment]
遇到同样问题了
canvas的tap和longpress不响应，去掉touchstart和touchend后可以响应
