### ISSUE TITLE
如何实现一个shape里draw 多个image?

### ISSUE THREAD

**Issue by zihyfw** [bobiscool/wxDraw#31]

**Comment by bobiscool** [comment]
？多个图片？你可以先拼接好再绘制可以吗？

**Comment by zihyfw** [comment]
不行啊.我的图可能无数种情况.比如我要拼个迷宫地图

**Comment by bobiscool** [comment]
无数种情况的话 你都攒成图片好像也有点不对吧 应该是绘最基本的元素 然后用数据去操作他来绘制

**Comment by zihyfw** [comment]
[https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1517828492515&di=677b6eb9d8e5e9bf3702f2a9c6d34424&imgtype=0&src=http%3A%2F%2Fphotocdn.sohu.com%2F20160316%2Fmp63681108_1458100887177_6.jpeg](url)
