### ISSUE TITLE
canvas绘制的多边形图形追加事件之后没有任何反应?

### ISSUE THREAD

**Issue by Xieguoiang** [bobiscool/wxDraw#34]
// 绘制多边形
let polygonNo1 = new Shape('polygon', {
      x: 50, y: 500, r: 20, sides: 6, //9边形
      fillStyle: "#CD661D", rotate: Math.PI
    }, 'mix', true)
//追加元素
  this.wxCanvas.add(polygonNo1)
//添加事件  没有任何效果？
    polygonNo1.bind('tap',function(){
      console.log(1)
    })
麻烦说下为什么 看你api也没有什么特殊的需要注意点啊

**Comment by Xieguoiang** [comment]
bindtouchstart: function (e) {
    // 检测手指点击开始事件
    this.wxCanvas.touchstartDetect(e);

  },
  bindtouchmove: function (e) {
    // 检测手指点击 之后的移动事件
    this.wxCanvas.touchmoveDetect(e);
  },
  bindtouchend: function () {
    //检测手指点击 移出事件
    this.wxCanvas.touchendDetect();
  },
  bindtap: function (e) {
    // 检测tap事件
    this.wxCanvas.tapDetect(e);
  },
  bindlongpress: function (e) {
    // 检测longpress事件
    this.wxCanvas.longpressDetect(e);
  },

你所说特殊事件函数 也写上了 
可是没有任何x效果

**Comment by bobiscool** [comment]
那你绑定事件到 wxml 上了么
```
<!--index.wxml-->
<view class="container">
 <canvas style="width: 400px; height: 500px;border:1px solid black;position:absolute;top:0px;left:0px;" canvas-id="rect"
  disable-scroll=true
  bindtouchstart="bindtouchstart"
  bindtouchmove="bindtouchmove"  
  bindtouchend="bindtouchend"
  bindtap="bindtap"
  bindlongpress="bindlongpress"
  ></canvas>
  
  
</view>
```

**Comment by Xieguoiang** [comment]
加了的wxml上面也加了的  还是不可以的
