### ISSUE TITLE
下载最新版本V1.101之后，circle的"sA"属性失灵了（已解决）

### ISSUE THREAD

**Issue by catshanshan** [bobiscool/wxDraw#37]
一开始我觉得是我写的代码有问题，打开demo之后仍然显示不对（并不是像吃豆人的形状，而是一刀切）
但我下载了旧版本的wxdraw.min文件，导入到项目里就是好的。

**Comment by catshanshan** [comment]
创建circle的时候将closePath置为true就好了

**Comment by bobiscool** [comment]
昨天本来想回 结果 被突然打断了  

解决了就好
