### ISSUE TITLE
两段动画先后播放，后面那个动画播不出来

### ISSUE THREAD

**Issue by catshanshan** [bobiscool/wxDraw#39]
在同一个wxDraw里先后播放两段动画，这两段动画之间有时间间隔，那么第二个动画就不会播放了~

**Comment by bobiscool** [comment]
用的 最新的 wxDraw.min.js？

**Comment by catshanshan** [comment]
是的哦~

**Comment by bobiscool** [comment]
可以贴一下代码吗 谢谢

**Comment by catshanshan** [comment]
drawDoubleScore:function(isUser){
    if(scoreDraw == null)
    {
      var scoreCanvas = wx.createCanvasContext('canvas-score');
      scoreDraw = new wxDraw(scoreCanvas, 0, 300, 800, 300);
    }

    // 绘制背景图片
    if(isUser)
    {
      let bgImg = new Shape('image', { x: 53, y: 80, w: 106, h: 28, file: game.data.imgUrl + "double_score.png" },
       'fill', true)
      scoreDraw.add(bgImg);
      let txt = new Shape('text', { x: 53, y: 80, text: "双倍得分", fontSize: 14, fillStyle: "#dbff78",
        align: "center", textBaseline: "middle"}, 'fill', true);
      scoreDraw.add(txt);

      bgImg.animate({ "x": "+=150" }, { duration: 1000 }).start();
      txt.animate({ "x": "+=150" }, { duration: 1000 }).start();
    }
    else
    {
      let bgImg = new Shape('image', { x: 322, y: 80, w: 106, h: 28, file: game.data.imgUrl + "double_score.png",
       rotate:Math.PI},'fill', true)
      scoreDraw.add(bgImg);
      let txt = new Shape('text', { x: 322, y: 80, text: "双倍得分", fontSize: 14, fillStyle: "#dbff78",
        align: "center", textBaseline: "middle"}, 'fill', true);
      scoreDraw.add(txt);

      bgImg.animate({ "x": "-=150" }, { duration: 1000 }).start();
      txt.animate({ "x": "-=150" }, { duration: 1000 }).start();
    }
  },

调用drawDoubleScore(true),会有图形从左边飞入屏幕
调用drawDoubleScore(false),会有图形从右边飞入屏幕
这两个方法一起调用的时候是好的，先后隔一秒再调用，后调用的方法里就不会执行动画。。
麻烦了~~
