### ISSUE TITLE
哪里没清干净事件?

### ISSUE THREAD

**Issue by zihyfw** [bobiscool/wxDraw#40]
Cannot read property 'getChoosed' of undefined;at pages/img/index page bindtouchstart function
TypeError: Cannot read property 'getChoosed' of undefined
    at WxDraw.getDetectedLayers (http://127.0.0.1:61190/appservice/util/wxdraw.js:4398:71)
    at http://127.0.0.1:61190/appservice/util/wxdraw.js:3617:35
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:61190/appservice/util/wxdraw.js:3613:32
    at Array.forEach (<anonymous>)
    at eventBus.dispatch (http://127.0.0.1:61190/appservice/util/wxdraw.js:3610:24)
    at Shape.detect (http://127.0.0.1:61190/appservice/util/wxdraw.js:3830:22)
    at WxDraw.<anonymous> (http://127.0.0.1:61190/appservice/util/wxdraw.js:4319:18)
    at Array.forEach (<anonymous>)
    at WxDraw.touchstartDetect (http://127.0.0.1:61190/appservice/util/wxdraw.js:4318:26)

**Comment by bobiscool** [comment]
http://project.ueflat.xyz/#/api/wxDraw  切换页面的时候清除画布了吗？

**Comment by zihyfw** [comment]
我没切换页面...
只是destroy一个shape之前又生成了一个一样的.(因为不能控制cshape位置)
代码如下
 that.createPolygonAgain(polygon.Shape.Option.x - e.rect_w / 2, polygon.Shape.Option.y - e.rect_h / 2, e.color, nextarr)
      e.unbind('touchstart',that.touchstart)
      e.unbind('touchmove')
      e.unbind('touchend')
      e.destroy()

**Comment by zihyfw** [comment]
touchend: function (e) {
    console.log(e.juxing+'++shape touchend++  ');

    var polygon=e.juxing
    var nextarr = []
    for (var i = 0; i < e.oldarr.length; i++) {
      nextarr[i] = []
      nextarr[i][0] = e.oldarr[i][0]
      nextarr[i][1] = e.oldarr[i][1]
    }

      that.createPolygonAgain(polygon.Shape.Option.x - e.rect_w / 2, polygon.Shape.Option.y - e.rect_h / 2, e.color, nextarr)
      e.unbind('touchstart',that.touchstart)
      e.unbind('touchmove')
      e.unbind('touchend')
      e.destroy()
  },
是在touchend 事件中触发的. 是因为这个原因吗?在外面删了再生成是没问题的.

**Comment by bobiscool** [comment]
你这里的 e 是代表的事件 还是 图形对象呀？
e 这样传进来应该是事件对象呀

**Comment by HuaZaiWuDi** [comment]
你好，为啥无法更改text，代码如下，修改没效果。
`
 text = new Shape('text', { x: width, y: 250, text: currentSteps.toString(), fillStyle: "#3cc51f", fontSize: 50 }, 'fill', true)
  text.updateText(currentSteps)
`

**Comment by bobiscool** [comment]
你添加到舞台上了吗？

**Comment by HuaZaiWuDi** [comment]
肯定有添加啊，修改圆环角度的时候没问题，但是修改text就不行了

**Comment by bobiscool** [comment]
没有报错？

**Comment by HuaZaiWuDi** [comment]
并没有报错，有报错就好解决了，你先试试你的库能不能更改，能更改就是我代码的问题，我在慢慢排除问题。麻烦了，谢谢。

**Comment by bobiscool** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
不好意思哈 现在在公司  公司电脑没那一套代码  部署环境比较麻烦    回家帮你看看



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年03月13日 14:30，HuaZaiWuDi<notifications@github.com> 写道： 


肯定有添加啊，修改圆环角度的时候没问题，但是修改text就不行了

**Comment by HuaZaiWuDi** [comment]
没事，谢谢了。先点个star，略表敬意

**Comment by HuaZaiWuDi** [comment]
打扰下，那个问题，有复现吗？，
