### ISSUE TITLE
在WePY框架下使用wxDraw报错

### ISSUE THREAD

**Issue by Blueria** [bobiscool/wxDraw#41]
在[WePY](https://tencent.github.io/wepy/index.html)框架下使用wxDraw时，报错，`Hello world`都做不到
### 使用大致如下：
```html
<canvas
    class="effect_canvas"
    canvas-id="effectCanvas"
    disable-scroll
></canvas>
```

```javascript
import wepy from 'wepy'
import { wxDraw as WxDraw, Shape } from '../plugins/wxdraw'

export default class Index extends wepy.page {
    data = {
        wxCanvas: null
    }

    onLoad() {
        const context = wx.createCanvasContext('effectCanvas')
        this.wxCanvas = new WxDraw(context, 0, 0, 400, 500)
    }
}
```

### 报错如下：
<img width="696" alt="wxdraw" src="https://user-images.githubusercontent.com/7038130/36074207-a2f328da-0f77-11e8-8b2b-fa25c2bb9770.png">

**Comment by Blueria** [comment]
自己解决了：
不能将`wxCanvas`放在`data`里，直接作为类属性即可（如下），`data`下的变量会被脏检查（此时会遇到问题）

```javascript
import wepy from 'wepy'
import { wxDraw as WxDraw, Shape } from '../plugins/wxdraw'

export default class Index extends wepy.page {
    wxCanvas =  null

    onLoad() {
        const context = wx.createCanvasContext('effectCanvas')
        this.wxCanvas = new WxDraw(context, 0, 0, 400, 500)
    }
}
```

**Comment by BoleLee** [comment]
在wepy项目中测试，无报错，但矩形画不出来；已经使用 @Blueria 的方法，但矩形同样没画出来；第一次使用wxDraw, 不知道原因，求助 @bobiscool

**Comment by BoleLee** [comment]
在wepy中，试用了画一个rect并加动画，正常；
改为画一个图片，无显示，没有报错，不知道原因；
在同一个canvas画两个rect, 其中一个设了动画，只显示了设动画的那个，且动画不进行，另一个则不显示，原因未明；

第一次使用wxDraw，求助 @bobiscool @Blueria
