### ISSUE TITLE
当为多个图形元素设置动画时，第二次设置的动画不动

### ISSUE THREAD

**Issue by xiamu14** [bobiscool/wxDraw#42]
微信开发工具版本：1.9.91
wxDraw.js 版本：latest
测试手机：iphone7 
测试微信版本：6.6.5
问题描述：我在 canvas 上添加多个图形元素（测试时使用的是 image），并同时为每个图形元素设置了两段动画。然而，第一段动画结束以后，第二段动画就不再执行。当我只为其中一个图形元素设置两段动画的时候，两段动画都可以执行。
录制视频：
![wxDraw.js issue-01](http://7xifdy.com1.z0.glb.clouddn.com/wxdraw-issue-01.gif)
代码如下：
`var context = wx.createCanvasContext("first"); //还记得 在wxml里面canvas的id叫first吗
      this.wxCanvas = new wxDraw(context, 0, 0, 400, 500);

      let img = new Shape("image", { x: 100, y: 300, w: 100, h: 100, file: "../../images/block@2x.png" }, "fill", true);
      let img2 = new Shape("image", { x: 10, y: 30, w: 100, h: 100, file: "../../images/block@2x.png" }, "fill", true);
      this.wxCanvas.add(img);//添加到canvas上面
      this.wxCanvas.add(img2);

      this.imgArr = [];
      this.imgArr.push(img);
      this.imgArr.push(img2);

      this.imgArr.forEach(img => {
          img
            .animate({ x: "+=100", y: "+=100" }, { duration: 1000 })
            .start(1);
    
        setTimeout(() => {
            img
                .animate({x: "-=100", y: "-=100"}, {duration: 1000}).start(1);
        }, 3000);
          
      });`

**Comment by bobiscool** [comment]
谢谢反馈  我会及时 处理的 现在在等高铁  _(:з」∠)_
