### ISSUE TITLE
destory 方法只能清除一个图形，再次调用清除另一图形无效

### ISSUE THREAD

**Issue by xiamu14** [bobiscool/wxDraw#43]
微信开发工具版本：1.9.91
wxDraw.js 版本：latest
测试手机：iphone7
测试微信版本：6.6.5

问题描述：当我希望清除掉 canvas 上所有的图形时，我只能使用 destory() 方法清除掉第一个图形，第二个图形调用 destory() 无效。

问题录频：
![](http://7xifdy.com1.z0.glb.clouddn.com/wxdraw-issue-02.gif)
代码：
`
      let img1 = new Shape("image", { x: 40, y: 80, w: 100, h: 100, file: "../../images/block@2x.png" }, "fill", true);
      let img2 = new Shape("image", { x: 100, y: 300, w: 100, h: 100, file: "../../images/block@2x.png" }, "fill", true);
      this.wxCanvas.add(img1);//添加到canvas上面
      this.wxCanvas.add(img2);

      this.imgArr = [];
      this.imgArr.push(img1);
      this.imgArr.push(img2);

      img1.destroy();
      img2.destroy();
`

**Comment by bobiscool** [comment]
你好 刚刚我用我的 试验了下  
![image](https://user-images.githubusercontent.com/9073321/36941641-115484ee-1f9b-11e8-9046-02672e45d543.png)

没有出现 你上述的问题呀  是有些细节不一样吗

**Comment by xiamu14** [comment]
我刚试了下，第二个图形还是存在，没有被清除。也不是又被重新添加上去的缘故。可以麻烦你把代码贴出来我对比下吗？

**Comment by bobiscool** [comment]
``` javascript
 aa:function(){ // 点击回调事件
    var self = this;
    this.rect2.destroy();
    setTimeout(function(){
      self.rect.destroy()
    },3000);
  },
  onLoad: function () {

    var context = wx.createCanvasContext('rect')



    this.wxCanvas = new wxDraw(context,0,0,400,500);


    this.rect = new Shape('image', { x: 150, y: 250, w: 80, h: 80,file:"./1.jpg",fillStyle:"#36BBA6" }, 'fill', true);

    this.rect2 = new Shape('image', { x: 150, y: 250, w: 80, h: 80, file: "./1.jpg", fillStyle: "#36BBA6" }, 'fill', true);

    this.wxCanvas.add(this.rect);
    this.wxCanvas.add(this.rect2);

    this.rect.updateOption({rotate:Math.PI/4})
}
```

**Comment by bobiscool** [comment]
确实 😭 我会花时间 找出问题的  谢谢

**Comment by xiamu14** [comment]
辛苦了，这个库写的非常棒。

**Comment by zwlcoding** [comment]
@xiamu14 我发现需要后进先出就没问题
```javascript
let a = new Shape('rect', ...set)
let b = new Shape('rect', ...set)

this.wxCanvas.add(a);
this.wxCanvas.add(b);


//这里如果这样执行，那 b 不会销毁 
a.destory()
b.destory()


//需要后添加的先销毁，这样执行才行
b.destory()
a.destory()

```
