### ISSUE TITLE
我做成粒子动画时有问题。时好时坏。请教一下什么问题

### ISSUE THREAD

**Issue by sunplum123** [bobiscool/wxDraw#44]
[我的粒子动画demo](https://github.com/sunplum123/particlesDemo)，有的时候最后的位置是正确的，有的时候最后的位置是错误的，也不清楚怎么回事，请教一下。 @bobiscool

**Comment by bobiscool** [comment]
这个的问题 实在不好意思 暂时还没想到好的解决办法  定时器那一块 微信好像 执行起来时间特别不准

**Comment by sunplum123** [comment]
@bobiscool 是什么情况导致的呢，其他的也没有这个问题撒。。
