### ISSUE TITLE
Shape对象的fillStyle会有默认颜色

### ISSUE THREAD

**Issue by dream2023** [bobiscool/wxDraw#5]
let circle = new Shape('circle', { x: 100, y: 100, r: 50, sA: -Math.PI / 1.5, eA: Math.PI / 1.5,strokeStyle: "#000000"});
像这种情况, 我只想描边, 并不想把整个圆都填充, 但默认是有黑色, 无法去除

**Comment by bobiscool** [comment]
默认是填充 你只需要设置填充方式为 stroke 就行了 
```
let circle = new Shape('circle', { x: 100, y: 100, r: 50, sA: -Math.PI / 1.5, eA: Math.PI / 1.5,strokeStyle: "#000000"},'stroke'); //在后面加一个 'stroke' 就行了

```

**Comment by dream2023** [comment]
问了一个比较白痴的问题, 但明明已经关闭了提问啊....
问一下, 什么时候能加上拖动图片, 即现在都是绘出来的图形, 如果我想拖动一下图片现在好像还不能实现
