### ISSUE TITLE
好像不支持canvas导入图片是吗，是微信那边不能好很好支持吗

### ISSUE THREAD

**Issue by masonwu311** [bobiscool/wxDraw#8]

**Comment by bobiscool** [comment]
对 微信那边只支持最简单的图片导入 不支持截取，所以本来想做精灵图动画的，见他 这个API功能太少了，所以暂时没做，如果他有支持截取我就会加上这个功能。

**Comment by Kongwsh** [comment]
小程序原生的ctx上下文不能用了？无法导入图片。

**Comment by bobiscool** [comment]
微信 是支持的 你看他的文档吧，但是功能太简单了所以我没支持。

**Comment by Kongwsh** [comment]
emmmm，我是说wxCanvas画布覆盖了canvas画布，画不出来惹

**Comment by Kongwsh** [comment]
你要不支持一下这个api吧，因为wxCanvas画布会覆盖小程序画布，在ctx上画不上去，所以也无法导入图片。

**Comment by bobiscool** [comment]
近期比较忙 ，可能要等段时间加上去，不好意思哈 _(:з」∠)_

**Comment by bobiscool** [comment]
![1](https://user-images.githubusercontent.com/9073321/33356132-c1961ed0-d4f5-11e7-86b7-c684a74d7bca.png)

已经支持 图片创建

**Comment by bobiscool** [comment]
![_-_document](https://user-images.githubusercontent.com/9073321/33356152-e085dad8-d4f5-11e7-9323-1f4cc901b422.png)
