### ISSUE TITLE
画圆的时候多了一条半径长度的边框

### ISSUE THREAD

**Issue by xcchcaptain** [bobiscool/wxDraw#9]
![image](https://user-images.githubusercontent.com/5080022/33606302-009d2a54-d9f8-11e7-9d6e-353842c92cd9.png)
`let epotinNo=new Shape('circle',{x:60,y:300,r:35,strokeStyle:"#cecece",lineWidth:3},'stroke',false);`
我想要的就是一个圆，多了个半径，不知道怎么解决呢。
画一个圆弧页会遇到同样的问题
难道需要再画一层盖住么 o(╯□╰)o

**Comment by bobiscool** [comment]
都不喜欢那条线呀 。。好的 明天解决

**Comment by xcchcaptain** [comment]
主要是和官方的api行为不一样了，多余的这条线，如果需要完全可以自己去加的啦

**Comment by bobiscool** [comment]
已经改了  添加一个 closePath 选项  默认为 false 也就不会添加那条线了
设置为 true 就会添加那条线。

图层这个是我自己设计出来的，canvas 本来就没有图层这个概念，需要用代码来实现

**Comment by xcchcaptain** [comment]
@bobiscool 感谢你及时的回复
建议 :把 canvasContext暴露出来，canvas转图片是一个很常用的业务场景
