### ISSUE TITLE
按照说明引入了mxdraw.min.js初始化后提示这些

### ISSUE THREAD

**Issue by linconz** [bobiscool/wxDraw#94]
mxDraw is not defined;at "pages/index/index" page lifeCycleMethod onLoad function
ReferenceError: mxDraw is not defined

**Comment by linconz** [comment]
<img width="819" alt="WX20190410-150248@2x" src="https://user-images.githubusercontent.com/2417911/55858289-e4eb5100-5ba1-11e9-8692-6dc2998d5a64.png">

**Comment by linconz** [comment]
原来是拼错了... mxDraw

**Comment by bobiscool** [comment]
这个是wxDraw.js啊 不是mxDraw Vicent Karl 邮箱：vicentkarl@gmail.com 签名由 网易邮箱大师 定制 在2019年04月10日 15:04，yilin.zhang 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
